name: Continuous integration

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # SETUP
      - name: Checkout
        uses: actions/checkout@v2

      - name: fake build
        run: cp README.md test.txt

      - name: Set the version
        id: version_number
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo ${GITHUB_REF#refs/tags/v}

      - name: Set the git source location
        id: source_loc
        run: |
          env > test.txt

      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: 'last-build'
          path: ./test.txt